# build inplace for unit tests to pass (since they are run from this
# top level directory we need the .so files to be in the src tree
# when they run.
build: clean
	python setup.py build_ext --inplace
	python setup.py build

clean:
	# lcs.cpp and blocks.cpp are generated by cython
	rm -rf build dist dragnet/*.pyc dragnet/*.so dragnet/lcs.cpp dragnet/blocks.cpp dragnet.egg-info dragnet/features/*.pyc dragnet/features/_kohlschuetter.cpp dragnet/features/_readability.cpp dragnet/features/_weninger.cpp

test: nose

nose:
	nosetests --exe --cover-package=dragnet --with-coverage --cover-branches -v --cover-erase

unittest:
	python -m unittest discover -s test

install: build
	python setup.py install

install-pip: build
	pip install .
