# build inplace for unit tests to pass (since they are run from this
# top level directory we need the .so files to be in the src tree
# when they run.
build: clean
	python setup.py build_ext --inplace
	python setup.py build

clean:
	# lcs.cpp is generated by cython
	rm -rf build dist dragnet/*.pyc dragnet/*.so dragnet/lcs.cpp

test: unittest

unittest:
	python -m unittest discover -s test

install: build
	python setup.py install
